/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.UserDAO;
import util.DBinit;

/**
 *
 * @author theos
 */
public class signup extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger
                        .getLogger(signup.class.getName());

        /**
         * Creates new form signup
         */
        public signup() {
                initComponents();
                this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panelSignup = new javax.swing.JPanel();
                txtUsername = new javax.swing.JTextField();
                username = new javax.swing.JLabel();
                password = new javax.swing.JLabel();
                RegisterLogin = new javax.swing.JButton();
                reset = new javax.swing.JButton();
                lblMessage = new javax.swing.JLabel();
                txtMessage = new javax.swing.JTextArea();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                BackToLogin = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                passwordtxt = new javax.swing.JPasswordField();
                confirmPasswordtxt = new javax.swing.JPasswordField();
                Emailtxt = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                userNametxt = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                panelSignup.setBackground(new java.awt.Color(255, 255, 255));
                panelSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

                txtUsername.addActionListener(this::txtUsernameActionPerformed);

                username.setText("Full Name");

                password.setText("Email");

                RegisterLogin.setBackground(new java.awt.Color(38, 114, 226));
                RegisterLogin.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
                RegisterLogin.setForeground(new java.awt.Color(255, 255, 255));
                RegisterLogin.setText("Register");
                RegisterLogin.setBorderPainted(false);
                RegisterLogin.addActionListener(this::RegisterLoginActionPerformed);

                reset.setBackground(new java.awt.Color(204, 204, 204));
                reset.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
                reset.setText("Reset");
                reset.setBorderPainted(false);
                reset.addActionListener(this::resetActionPerformed);

                lblMessage.setForeground(new java.awt.Color(255, 51, 0));
                lblMessage.setAutoscrolls(true);

                txtMessage.setColumns(20);
                txtMessage.setRows(5);
                txtMessage.setText("  Fill in all Fileds to create a lecturer account");

                jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

                jLabel1.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
                jLabel1.setText("Student Management System");

                jLabel3.setIcon(new javax.swing.ImageIcon(
                                getClass().getResource("/ui/school_65dp_000000_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addContainerGap(53, Short.MAX_VALUE)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1)
                                                                                .addGroup(jPanel2Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(69, 69, 69)
                                                                                                .addComponent(jLabel3)))
                                                                .addContainerGap(53, Short.MAX_VALUE)));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(18, Short.MAX_VALUE)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel1)
                                                                .addGap(27, 27, 27)));

                jPanel1.setBackground(new java.awt.Color(38, 114, 226));

                jLabel2.setFont(new java.awt.Font("Adwaita Sans", 1, 15)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("Student Management System - lecturer registration");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap(158, Short.MAX_VALUE)
                                                                .addComponent(jLabel2)
                                                                .addContainerGap(159, Short.MAX_VALUE)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));

                BackToLogin.setForeground(new java.awt.Color(38, 114, 226));
                BackToLogin.setText("Back to login");
                BackToLogin.addActionListener(this::BackToLoginActionPerformed);

                jLabel4.setText("Password");

                jLabel5.setText("Confirm");

                passwordtxt.addActionListener(this::passwordtxtActionPerformed);

                Emailtxt.addActionListener(this::EmailtxtActionPerformed);

                jLabel6.setText("User Name");

                userNametxt.setMargin(new java.awt.Insets(0, 6, 0, 6));

                javax.swing.GroupLayout panelSignupLayout = new javax.swing.GroupLayout(panelSignup);
                panelSignup.setLayout(panelSignupLayout);
                panelSignupLayout.setHorizontalGroup(
                                panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(panelSignupLayout.createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(panelSignupLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(panelSignupLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(36, 36, 36)
                                                                                                .addGroup(panelSignupLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(panelSignupLayout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(panelSignupLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGroup(panelSignupLayout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                .addComponent(username)
                                                                                                                                                                .addComponent(password)
                                                                                                                                                                .addGroup(panelSignupLayout
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                                                .addComponent(jLabel4))
                                                                                                                                                                .addComponent(jLabel6))
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addGroup(panelSignupLayout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                false)
                                                                                                                                                                .addComponent(txtUsername,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                165,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(passwordtxt)
                                                                                                                                                                .addComponent(confirmPasswordtxt)
                                                                                                                                                                .addComponent(Emailtxt)
                                                                                                                                                                .addComponent(userNametxt)))
                                                                                                                                .addGroup(panelSignupLayout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(2, 2, 2)
                                                                                                                                                .addComponent(RegisterLogin)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                .addComponent(reset,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                100,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addComponent(txtMessage,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                255,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addComponent(jPanel2,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(panelSignupLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(116, 116, 116)
                                                                                                .addComponent(BackToLogin)))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(panelSignupLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(panelSignupLayout.createSequentialGroup()
                                                                                .addGap(207, 207, 207)
                                                                                .addComponent(lblMessage)
                                                                                .addContainerGap(403,
                                                                                                Short.MAX_VALUE))));
                panelSignupLayout.setVerticalGroup(
                                panelSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSignupLayout
                                                                .createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(panelSignupLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtUsername,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(username))
                                                                .addGap(14, 14, 14)
                                                                .addGroup(panelSignupLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(password)
                                                                                .addComponent(Emailtxt,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(panelSignupLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(userNametxt,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(panelSignupLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(passwordtxt,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(panelSignupLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(confirmPasswordtxt,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(panelSignupLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(RegisterLogin)
                                                                                .addComponent(reset))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(txtMessage,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                26,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(BackToLogin)
                                                                .addContainerGap(20, Short.MAX_VALUE))
                                                .addGroup(panelSignupLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(panelSignupLayout.createSequentialGroup()
                                                                                .addGap(179, 179, 179)
                                                                                .addComponent(lblMessage)
                                                                                .addContainerGap(245,
                                                                                                Short.MAX_VALUE))));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(panelSignup, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(panelSignup, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void BackToLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BackToLoginActionPerformed
                new Login().setVisible(true);
                this.dispose();
        }// GEN-LAST:event_BackToLoginActionPerformed

        private void resetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetActionPerformed
                txtUsername.setText("");
                Emailtxt.setText("");
                userNametxt.setText("");
                passwordtxt.setText("");
                confirmPasswordtxt.setText("");
                txtMessage.setText("  Fill in all fields to create a lecturer account.");
        }// GEN-LAST:event_resetActionPerformed

        private void RegisterLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterLoginActionPerformed
                String fullName = txtUsername.getText().trim();
                String email = Emailtxt.getText().trim();
                String username = userNametxt.getText().trim();
                String password = new String(passwordtxt.getPassword()).trim();
                String confirm = new String(confirmPasswordtxt.getPassword()).trim();

                if (fullName.isEmpty() || email.isEmpty() || username.isEmpty() || password.isEmpty()
                                || confirm.isEmpty()) {
                        txtMessage.setText("  Please fill in all fields.");
                        return;
                }

                if (!password.equals(confirm)) {
                        txtMessage.setText("  Passwords do not match.");
                        return;
                }

                RegisterLogin.setEnabled(false);
                reset.setEnabled(false);

                java.awt.EventQueue.invokeLater(() -> {
                        try {
                                DBinit.init();

                                UserDAO dao = new UserDAO();
                                boolean ok = dao.register(fullName, email, username, password);

                                if (ok) {
                                        txtMessage.setText("  Account created! You can now log in.");
                                        javax.swing.JOptionPane.showMessageDialog(
                                                        this,
                                                        "Lecturer account created successfully!\nYou can now log in with: "
                                                                        + username,
                                                        "Registration Successful",
                                                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                                        new Login().setVisible(true);
                                        dispose();
                                } else {
                                        txtMessage.setText("  Username '" + username + "' is already taken.");
                                        RegisterLogin.setEnabled(true);
                                        reset.setEnabled(true);
                                }
                        } catch (Exception ex) {
                                txtMessage.setText("  Error: " + ex.getMessage());
                                RegisterLogin.setEnabled(true);
                                reset.setEnabled(true);
                        }
                });
        }// GEN-LAST:event_RegisterLoginActionPerformed

        private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUsernameActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtUsernameActionPerformed

        private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordtxtActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_passwordtxtActionPerformed

        private void EmailtxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EmailtxtActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_EmailtxtActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
                        logger.log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new signup().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BackToLogin;
        private javax.swing.JTextField Emailtxt;
        private javax.swing.JButton RegisterLogin;
        private javax.swing.JPasswordField confirmPasswordtxt;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JLabel lblMessage;
        private javax.swing.JPanel panelSignup;
        private javax.swing.JLabel password;
        private javax.swing.JPasswordField passwordtxt;
        private javax.swing.JButton reset;
        private javax.swing.JTextArea txtMessage;
        private javax.swing.JTextField txtUsername;
        private javax.swing.JTextField userNametxt;
        private javax.swing.JLabel username;
        // End of variables declaration//GEN-END:variables
}
